from tkinter import *
def add():
    sum=int(e1.get())+int(e2.get())
    e3.insert(0,str(sum))
def subtract():
    sub=int(e1.get())-int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(sub))
def product():
    multi=int(e1.get())*int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(multi))
def division():
    div=int(e1.get())/int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(div))
        
window=Tk()
window.title("welcome")
window.geometry("400x500")
window.resizable(False,False)
window.configure(background="#54b3d3")
window.attributes("-topmost",True)
window.attributes("-alpha",0.9)
window.iconbitmap("favicon.ico")
lbl1=Label(text="enter 1st number")
lbl1.place(x=50,y=20)
lbl2=Label(text="enter 2nd number")
lbl2.place(x=50,y=45)
e1=Entry()
e1.place(x=150,y=20)
e2=Entry()
e2.place(x=155,y=45)
e3=Entry() 
e3.place(x=120,y=130)
btn1=Button(text="sum",command=add)
btn1.place(x=150,y=90)
btn2=Button(text="sub",command=subtract)
btn2.place(x=200,y=90)
btn3=Button(text="multi",command=product)
btn3.place(x=250,y=90)
btn4=Button(text="div",command=division)
btn4.place(x=300,y=90)
window.mainloop()